### ISSUE TITLE
www.tensorflow.org

### ISSUE THREAD

**Issue by hzhangxyz** [ustclug/light-list#1]
Tensorflow cannot be accessed via China Mobile Net and China Telecom Net

**Comment by hzhangxyz** [comment]
And magenta.tensorflow.org

**Comment by gaoyifan** [comment]
<del>这只是陈述了一个事实..... 并不是issue啊......</del>
<del>BTW, 我在中国电信网络中可以正常访问www.tensorflow.org</del>
抱歉，我的测试不足。确认访问无法访问。

**Comment by gaoyifan** [comment]
已添加。请尝试更新PAC文件。
